#! /usr/bin/python

import argparse
import logging
import matplotlib.pyplot as plt

from glue import lal
from pycbc import frame
from pycbc import types

# initializations
channel_name = 'L1:OAF-CAL_DARM_DQ'

# setup log
logging_level = logging.DEBUG
logging.basicConfig(format='%(asctime)s : %(message)s', level=logging_level)

# read frame cache
logging.info('Reading cache file...')
frame_cache = lal.Cache.fromfilenames(['frame_caches/L1-DATAFIND-1102660000-200.lcf'])
frame_filenames = [entry.path for entry in frame_cache]

# get channel data from frame files
logging.info('Reading frame files...')
data = frame.read_frame(frame_filenames, channel_name, start_time=1102660000, end_time=1102660200)
data.save('output/frame.txt')

# plot
timeseries = types.load_timeseries('output/frame.txt')
plt.plot(timeseries.sample_times, timeseries.numpy())
print 'showing plot'
plt.show()
